### ISSUE TITLE
タイトル画面の作成(仮)

### ISSUE THREAD

**Issue by sotaryota** [MiyabaraYouta/Unreal_VRProject#28]
タイトルからゲーム画面への推移と推移の際のホワイトアウトの実装

**Comment by ishizuka0106** [comment]
https://user-images.githubusercontent.com/107675552/184341517-935fa04b-5972-4a85-9c2b-a01843ba1544.mp4

とりあえずスペースキーを押したら遷移するようにしました。
添付した動画のような感じにしましたがこれでよろしいでしょうか？

**Comment by MiyabaraYouta** [comment]
確認しました。ありがとうございます。
