### ISSUE TITLE
gitの使い方

### ISSUE THREAD

**Issue by MiyabaraYouta** [MiyabaraYouta/Unreal_VRProject#9]
gitの使い方についてTextで送ってほしいです。

出来れば過程にして欲しいです
１．～する
２．～する

みたいに簡単な感じでいいです。

後で、僕の方でまとめてDisCordにアップします。
僕よりデニス君の方が知ってると思うのでよろしくお願いします。

**Comment by tomohiro-nozue-jec** [comment]
@MiyabaraYouta 
Wikiの方に書いてもらっていいですか?

**Comment by ShumkovD** [comment]
とりあえず、Issueの解決し方を作りました。
明確に作業の流れを説明していると思います。

レポのクローンし方を説明する必要があるでしょうか？
[Issueの解決し方.docx](https://github.com/MiyabaraYouta/Unreal_VRProject/files/8997373/Issue.docx)

**Comment by ShumkovD** [comment]
GITをインストールするときに気を付けなければならないことと、プロジェクトのクローンし方をまとめました
[GITインストール.docx](https://github.com/MiyabaraYouta/Unreal_VRProject/files/8998535/GIT.docx)

**Comment by MiyabaraYouta** [comment]
githubのwikiにあげた
